service: serverless-fiap
frameworkVersion: '>=1.1.0 <=2.38.0'
plugins:
  - serverless-offline

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  region: ${opt:region, 'us-east-1'}
  environment:
    TABLE_NAME: fiap-trips
  timeout: 30

functions:
  register:
    handler: src/index.saveTrip
    memorySize: 500
    description: Register a new trip
    events:
      - http:
          path: /trip
          method: POST
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  
package:
  include:
    - node_modules/**/node_modules/**/*.js
    - node_modules/**/node_modules/**/package.json
  exclude:
    - .vscode/**
    - .gitignore
    - gulpfile.js
    - package-lock.json
    - node_modules/**/aws-sdk/**
    - node_modules/**/bin/**
    - node_modules/**/.editorconfig
    - node_modules/**/.eslintrc.js
    - node_modules/**/.travis.yml
    - node_modules/**/.eslintrc
    - node_modules/**/.jscsrc
    - node_modules/**/.jshintignore
    - node_modules/**/license.txt
    - node_modules/**/tsconfig.json
    - node_modules/**/workspace.json
    - node_modules/**/*.md
    - node_modules/**/*.ts
    - node_modules/**/*.markdown
    - node_modules/**/.npmignore
    - node_modules/**/.jshintrc
    - node_modules/**/LICENSE
    - node_modules/**/LICENCE
    - node_modules/**/license
    - node_modules/**/Makefile
    - node_modules/**/yarn.lock
    - node_modules/**/package-lock.json
    - node_modules/**/*.map
    - node_modules/**/test/**
    - node_modules/**/.vscode/**
    - node_modules/**/tests/**
    - node_modules/**/benchmark/**
    - node_modules/**/scripts/**
    - node_modules/**/__tests__/**
    - node_modules/**/*.min.js